metadata.format.version = "1.1"

[versions]

# plugins
shadow = "7.1.2"
blossom = "1.3.1"
spotless = "6.11.0"

# general
gson = "2.10"
netty = "4.1.84.Final"
annotations = "23.0.0"
event = "5.0.0-SNAPSHOT"

# platform api versions
sponge = "10.0.0"
minestom = "42195c536b"
nukkitX = "1.0-SNAPSHOT"
paper = "1.19.2-R0.1-SNAPSHOT"

# platform extensions
paperLib = "1.0.7"
packetEvents = "2.0-SNAPSHOT"
protocolLib = "master-SNAPSHOT"


[libraries]

# general
event = { group = "net.kyori", name = "event-api", version.ref = "event" }
netty = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# platform api
nukkitX = { group = "cn.nukkit", name = "nukkit", version.ref = "nukkitX" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }
minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

# platform extensions
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
protocolLib = { group = "com.github.dmulloy2", name = "ProtocolLib", version.ref = "protocolLib" }
packetEvents = { group = "com.github.retrooper.packetevents", name = "spigot", version.ref = "packetEvents" }


[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
